### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by YellowThree-HS** [sharif1093/py_floor_plan_segmenter#2]
Hello, may I ask what dataset you are using? I don't seem to have found it online. Did you create it yourself?

**Comment by sharif1093** [comment]
Two datasets are used for benchmarking our method. The first dataset is from [Bormann et al.](https://ieeexplore.ieee.org/document/7487234). The second benchmark is using real maps from D8/9/10 vacuum cleaning robots, Neato Robotics. The second benchmark is published for the first time. Please refer to the [paper](https://arxiv.org/abs/2303.13798) for more information regarding the benchmarks.
